# CH-4. LOOPS

## 4.1 While Loop

 
The while loop is like a repeated if statement. The code is executed over and over again, as long as the condition is True. Have another look at its recipe.

        while condition :
            expression
    

WL is Numerically calculating model

"repeating action until condition is met”

Example:

    ● Error starts at 50
    ● Divide error by 4 on every run
    ● Continue until error no longer > 1

**EXERCISE-1: Basic while loop**

Create the variable offset with an initial value of 8.

Code a while loop that keeps running as long as offset is not equal to 0. 

Inside the while loop:
Print out the sentence "correcting...".

Next, decrease the value of offset by 1. You can do this with offset = offset - 1.
Finally, still within your loop, print out offset so you can see how it changes.

In [1]:
# Initialize offset
offset = 8

# Code the while loop
while offset != 0:
    print("correcting...")
    offset = offset-1
    print(offset)

correcting...
7
correcting...
6
correcting...
5
correcting...
4
correcting...
3
correcting...
2
correcting...
1
correcting...
0


**EXERCISE-2: While Loop + Conditionals**

Inside the while loop, complete the if-else statement:

If offset is greater than zero, you should decrease offset by 1.

Else, you should increase offset by 1.

If you've coded things correctly, hitting Submit Answer should work this time.

In [2]:
# Initialize offset
offset = -6

# Code the while loop
while offset != 0 :
    print("correcting...")
    if offset>0 :
        offset = offset-1
    else : 
        offset = offset +1
    print(offset)

correcting...
-5
correcting...
-4
correcting...
-3
correcting...
-2
correcting...
-1
correcting...
0


## 4.2 for loops

### Loop over a list

**Exercise-3: for Loops**

Write a for loop that iterates over all elements of the areas list and prints out every element separately.

In [3]:
# areas list
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Code the for loop
for x in areas:
    print(x)

11.25
18.0
20.0
10.75
9.5


### Loop with Indexes and values

Using a for loop to iterate over a list only gives you access to every list element in each run, one after the other. 

If you also want to access the index information, so where the list element you're iterating over is located, you can use `enumerate()`.

`enumerate()` produces two values:
    
    i. the index: placed on the first variable on the for loop
    ii. and the value: placed on the second value on the variable list of for loop

**Exercise-4: Loop with index**

Adapt the for loop in the sample code to use enumerate() and use two iterator variables.

Update the print() statement so that on each run, a line of the form "room x: y" should be printed, where x is the index of the list element and y is the actual list element, i.e. the area. 

Make sure to print out this exact string, with the correct spacing.

In [5]:
# areas list
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Change for loop to use enumerate() and update print()
for index, value in enumerate(areas) :
    print("room"+ str(index)+":"+str(value))

room0:11.25
room1:18.0
room2:20.0
room3:10.75
room4:9.5


Adapt the print() function in the for loop on the right so that the first printout becomes 

"room 1: 11.25", the second one "room 2: 18.0" and so on.

In [6]:
# areas list
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

# Code the for loop
for index, area in enumerate(areas) :
    print("room " + str(index+1) + ": " + str(area))

room 1: 11.25
room 2: 18.0
room 3: 20.0
room 4: 10.75
room 5: 9.5


### Loop over list of lists

Remember the house variable from the Intro to Python course? 

Have a look at its definition on the right. It's basically a list of lists, where each sublist contains the name and area of a room in your house.

It's up to you to build a for loop from scratch this time!

**Exercise-5: Loop over list of lists**

Write a for loop that goes through each sublist of house and prints out the x is y sqm, where x is the name of the room and y is the area of the room.

In [50]:
# house list of lists
house = [["hallway", 11.25], 
         ["kitchen", 18.0], 
         ["living room", 20.0], 
         ["bedroom", 10.75], 
         ["bathroom", 9.50]]
         
print("the "+house[1][0]+" is "+ str(house[1][1])+" sqm") 
print("the "+house[2][0]+" is "+ str(house[2][1])+" sqm")
print("the "+house[3][0]+" is "+ str(house[3][1])+" sqm")
print("the "+house[4][0]+" is "+ str(house[4][1])+" sqm")

the kitchen is 18.0 sqm
the living room is 20.0 sqm
the bedroom is 10.75 sqm
the bathroom is 9.5 sqm


In [51]:
for x in house:
    print("the " + x[0] + " is " + str(x[1]) + " sqm")

the hallway is 11.25 sqm
the kitchen is 18.0 sqm
the living room is 20.0 sqm
the bedroom is 10.75 sqm
the bathroom is 9.5 sqm
